set keep-alive defaults for new connections
j123b567/scpi-parser pull request #128
Opened 2021-11-06 14:17 UTC by MisterHW

Configure scpi-specific keep-alive settings for new connections. Without these, a connection lost on the client side blocks the server baiscally indefinitely, requiring a reset or some means to recover via another port or interface.

scpi server connection timeout is chosen such that when idle, zero window probes are sent periodically, and the connection is closed when they fail SCPI_KEEP_CNT times.

also requires (lwipopts.h):
```
set #define LWIP_TCP_KEEPALIVE 1
```

call` tcp_tmr();` every 250 ms (e.g. via` xTimerCreate()`, `xTimerStart()` in callback).

---

FreeRTOS example:

```
#include "tcp_priv.h"

#define NUM_TIMERS 1
TimerHandle_t xTimers[ NUM_TIMERS ];

void tcp_tmr_callback( TimerHandle_t xTimer ){
    configASSERT( xTimer );
    tcp_tmr();
}

bool Timer_Init(unsigned int number, unsigned int interval, TimerCallbackFunction_t callback){
    configASSERT(number < NUM_TIMERS);
    if(number >= NUM_TIMERS){
        // Index out of range.
        return false;
    }
    xTimers[ number ] = xTimerCreate (
        "Timer", /* Just a text name, not used by the RTOS kernel. */
        interval, /* The timer period in ticks, must be greater than 0. */
        pdTRUE, /* The timers will auto-reload themselves when they expire. */
        ( void * ) 0, /* pvTimerID is used to store a count of
            * the number of times the timer has expired, which is initialised to 0. */
        callback /* callback called when it expires. */
        );

    if( xTimers[ number ] != NULL ) {
        /* Start the timer. No block time is specified, and even if one was it would be
         * ignored because the RTOS scheduler has not yet been started. */
        if( xTimerStart( xTimers[ number ], 0 ) == pdPASS )
        {
            /* Timer successfully created and set into the Active state. */
            return true;
        }
    }

    return false;
}

bool Timers_Init(){
    bool result = true;
    result &= Timer_Init( 0, 250, tcp_tmr_callback );
    // other timers ...
    return result;
}
```

To change the defaults for all connections, add these values (lwipopts.h):

```
#define  TCP_KEEPIDLE_DEFAULT   15000UL /* Default KEEPALIVE timer in milliseconds */
#define  TCP_KEEPINTVL_DEFAULT   5000UL /* Default Time between KEEPALIVE probes in milliseconds */
#define  TCP_KEEPCNT_DEFAULT        3U  /* Default Counter for KEEPALIVE probes */
```

Also note: when other connections are used (e.g. http server listening socket), revisit memory pool sizes (lwipopts.h):
```
#define MEMP_NUM_NETCONN 10
```
(default is 4, which can be exhausted by scpi server when two connections are active on top of the two listening socket protocol control block (pcb) structs which stay allocated.

2021-11-08 08:40 UTC, j123b567 commented
The PR is probably ok, but you have something wrong with your LwIP configuration.

In the first place, from FreeRTOS, you should never ever call raw api functions directly (like `tcp_tmr`).

You should probably just define `LWIP_TIMERS` in the `lwipopts.h` and it will just start working without separate thread.

When not using RTOS, one should call `sys_check_timeouts` in the main loop, which will call other timers and also the tcp one. When RTOS (`NO_SYS=0`) is used, it is done by tcpip thread itself (needs `LWIP_TIMERS` to be enabled).

2021-11-08 09:35 UTC, MisterHW commented
Thank for for the hint. Both USE\_TIMERS and LWIP_TIMERS are enabled, and it appears that changes got lost between modifying defines directly, and regenerating them via STM32CubeMX - leading me to believe additionally calling tcp_tmr() would be necessary. 
I verified it's working as per your description (I removed the redundant call to tcp_tmr() ) and will update my documentation and the PR description later.

2021-11-09 10:34 UTC, j123b567 requested changes

2021-11-09 10:34 UTC, j123b567 commented on examples/test-LwIP-netconn/scpi_server.c
> +            newconn->pcb.tcp->so_options |= SOF_KEEPALIVE;
Probably `ip_set_option` should be used as lwip sintactic sugar and not directly accessing `so_options`. Same for control connection.

```c
ip_set_option(newconn->pcb.tcp, SOF_KEEPALIVE);
```

2021-11-09 13:22 UTC, j123b567 approved these changes

2021-11-09 13:35 UTC, merged